name: Build Release
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get GitHub slug info
        uses: rlespinasse/github-slug-action@3.5.1

      - name: Pack it up!
        run: tar --exclude-vcs --exclude='./.github' -czf /tmp/${{ github.event.repository.name }}-${{ env.GITHUB_SHA_SHORT }}-${{ env.GITHUB_REF_SLUG_CS }}.crbl .

      - name: Upload pack to Packs Dispensary
        run: |
          curl --location '${{ vars.DISPENSARY_ENDPOINT }}/${{ github.event.repository.name }}' \
            --header 'Authorization: Bearer ${{ secrets.PACKS_API_TOKEN }}' \
            --form "file=@/tmp/${{ github.event.repository.name }}-${{ env.GITHUB_SHA_SHORT }}-${{ env.GITHUB_REF_SLUG_CS }}.crbl" \
